### ISSUE TITLE
Problems listing alerts after upgrade of zabbix to 2.2

### ISSUE THREAD

**Issue by xen0l** [erigones/Ludolph#16]
The following traceback is returned:
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1601, in _threaded_event_wrapper
    func(*args)
  File "/usr/lib/python2.6/site-packages/ludolph/bot.py", line 412, in message
    out = f_cmd(msg)
  File "/usr/lib/python2.6/site-packages/ludolph/plugins/zabbix.py", line 41, in wrap
    return fun(obj, msg, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ludolph/command.py", line 81, in wrap
    out = fun(obj, msg, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/ludolph/plugins/zabbix.py", line 183, in alerts
    if trigger['error'] or int(trigger['value_flags']):
KeyError: 'value_flags'
```

**Comment by dn0** [comment]
Fixed in commit d8f3af0d
