### ISSUE TITLE
ability to set Avatar

### ISSUE THREAD

**Issue by ricco386** [erigones/Ludolph#19]
Add ability to set avatar.

**Comment by ricco386** [comment]
Tested on ejabberd and works fine, unfortunatelly this doesnt works with google accounts, it return following error:
<error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error>

**Comment by ricco386** [comment]
Python3 problem when reading files:

```
2015-03-23 16:20:13,334 ERROR    sleekxmpp.xmlstream.xmlstream: Error processing event handler: <bound method LudolphBot.message of <ludolph.bot.LudolphBot object at 0x7f5f51a37cf8>>
Traceback (most recent call last):
  File "/home/ricco/Erigones/Ludolph/envs3/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1645, in _threaded_event_wrapper
    func(*args)
  File "/home/ricco/Erigones/Ludolph/ludolph/bot.py", line 414, in message
    out = f_cmd(msg)
  File "/home/ricco/Erigones/Ludolph/ludolph/command.py", line 154, in wrap
    return fun(obj, msg, *args, **kwargs)
  File "/home/ricco/Erigones/Ludolph/ludolph/command.py", line 138, in wrap
    return fun(obj, msg, *params, **kwargs)
  File "/home/ricco/Erigones/Ludolph/ludolph/command.py", line 86, in wrap
    out = fun(obj, msg, *args, **kwargs)
  File "/home/ricco/Erigones/Ludolph/ludolph/plugins/base.py", line 170, in avatar_set
    avatar = avatar_file.read()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by ricco386** [comment]
Python3 problem has been reported to SleekXMPP library: https://github.com/fritzy/SleekXMPP/issues/353 and pull request with fix has been created: https://github.com/fritzy/SleekXMPP/pull/354
